// <auto-generated />
using System;
using Jaiz_CSAT_Survey.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jaiz_CSAT_Survey.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701103546_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jaiz_CSAT_Survey.Models.SurveyAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SurveyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyAlerts");
                });

            modelBuilder.Entity("Jaiz_CSAT_Survey.Models.SurveyResponse", b =>
                {
                    b.Property<long>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SurveyId"));

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("BranchAmbience")
                        .HasColumnType("tinyint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("IssueResolution")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ProductRating")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RecommendationLikelihood")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ServiceSatisfaction")
                        .HasColumnType("tinyint");

                    b.Property<string>("Staff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("StaffProfessionalism")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SurveyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("TransactionEase")
                        .HasColumnType("tinyint");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("WebRating")
                        .HasColumnType("tinyint");

                    b.HasKey("SurveyId");

                    b.ToTable("SurveyResponses", (string)null);
                });

            modelBuilder.Entity("Jaiz_CSAT_Survey.Models.SurveyAlert", b =>
                {
                    b.HasOne("Jaiz_CSAT_Survey.Models.SurveyResponse", null)
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
